name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  pre-commit-lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Check out source repository
        uses: actions/checkout@v5

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Main Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libhunspell-dev \
            hunspell \
            jq \
            shellcheck \
            git \
            ca-certificates \
            apt-transport-https

          # Install bearer CLI
          sudo update-ca-certificates
          echo -e "Types: deb\nURIs: https://apt.fury.io/bearer/\nSuites: /\nTrusted: yes" | sudo tee /etc/apt/sources.list.d/fury.sources
          sudo apt-get update
          sudo apt-get install bearer

          npm install -g markdownlint-cli cspell
      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pre-commit
        run: pre-commit run --all --verbose

      - name: Analysis (git diff)
        if: failure()
        run: git diff
