name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  pre-commit-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v5
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all --verbose
      - name: Analysis (git diff)
        if: failure()
        run: git diff
