name: Generate resources.py

on: workflow_dispatch

jobs:
  pyrcc5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install PyQt5
      - run: pyrcc5 planet_explorer/resources/resources.qrc -o planet_explorer/resources/resources.py
