name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  # Run unit tests
  test:
    # TODO: Test on 26.05
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # qgis_version: [ "4.0", "3.44" ]
        qgis_version: [ "4.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-qemu-action@v4

      - name: Test on QGIS
        env:
          PLANET_USER: ${{ secrets.PLANET_USER }}
          PLANET_PASSWORD: ${{ secrets.PLANET_PASSWORD }}
          QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
        run: |
          docker compose -f .docker/docker-compose.gh.yml build qgis

          docker compose -f .docker/docker-compose.gh.yml run \
            -e "PLANET_USER=${PLANET_USER}" \
            -e "PLANET_PASSWORD=${PLANET_PASSWORD}" \
            qgis /usr/src/.docker/run-docker-tests.sh
